scrape_configs:
  - job_name: 'bot-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8091']

  - job_name: 'scrapper-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:8098' ]
